name: Child Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - staging
          - prod
        required: true

  workflow_run:
    workflows: ["Parent Workflow"]
    types:
      - completed

jobs:
  child_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Parent Workflow ID: ${{ github.event.workflow_run.workflow_id }}"
          echo "Parent Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Parent Workflow Name:  ${{ github.event.workflow_run.name }}"

      - name: Conditional Step 1
        if: |
          (github.event.workflow_run.name == 'Parent Workflow' && github.event.workflow_run.conclusion == 'success')
        run: |
          echo "Conditional Step 2"
          echo "Id match: ${{ github.event.workflow_run.workflow_id == 'Parent Workflow' }}"
          echo "Name match: ${{ github.event.workflow_run.name == 'Parent Workflow' }}"
          echo "Conclusion match: ${{ github.event.workflow_run.conclusion == 'success' }}"

      - name: Conditional Step 2
        if: |
          ${{ github.event.workflow_run.name == 'Parent Workflow' && github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "Conditional Step 2"
          echo "Id match: ${{ github.event.workflow_run.workflow_id == 'Parent Workflow' }}"
          echo "Name match: ${{ github.event.workflow_run.name == 'Parent Workflow' }}"
          echo "Conclusion match: ${{ github.event.workflow_run.conclusion == 'success' }}"
